### ISSUE TITLE
Version in interface wasn't incremented to 1.9.12

### ISSUE THREAD

**Issue by OrGoN3** [Decscots/Lockpick_RCM#2]
Just superficial. The header still says 1.9.11.

**Comment by muxi1** [comment]
Here is Lockpick_RCM with the correct version number
[Lockpick_RCM.zip](https://github.com/Decscots/Lockpick_RCM/files/14789033/Lockpick_RCM.zip)

**Comment by Decscots** [comment]
Thank you. I have updated the release binary.
