### ISSUE TITLE
No titles found when using. 

### ISSUE THREAD

**Issue by Arctic-77** [Decscots/Lockpick_RCM#3]
The Switch software is set to 18.0.0 to match the lockpick version. I am using a hardware modded switch running atmosphere 1.7.1, Hekate 6.2.0. 
When using Lockpick from payloads, it doesn't get any of the title keys, but it does get prodkeys. Is there something I am missing?

**Comment by impeeza** [comment]
You can select EmuNAND or SYSNAND,  be sure you are dumping the Title keys for the right xNAND

**Comment by Arctic-77** [comment]
Yea I figured it out, the title keys weren’t showing up because I didn’t
have any games downloaded, but as soon as I did title keys showed up.

Contact me via email primarily.
Thank you in advance.

**Comment by impeeza** [comment]
Please close the Issue.
